### ISSUE TITLE
Increase the length of characters for state code

### ISSUE THREAD

**Issue by Gabbydamian** [SogoAG/Nigeria-state-Capital#1]
## Issue Title
Increase the length of characters for state code

### Description
I'm am suggesting we increase the number of characters for each state's code for better legibility and recognition. It would also help to avoid duplicate codes for states with similar names.

### Current State
for example. State code for Abuja is 'AB'

### Proposed Change
changing state code for Abuja from 'AB' to 'ABJ' 

### Rationale
It is easily recognizable as it hold more characters from the original state name

### Your Contribution (optional)
I'm willing to edit the codes for each state

**Comment by SogoAG** [comment]
Yeah makes perfect sense that way
